name: build

on:

  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:

  build_linux:
    runs-on: ubuntu-20.04

    env:
      BUILD_TYPE: relwithdebinfo

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare docker image
      run: ci/prepare.sh

    - name: Install tools
      run: ci/install.sh

    - name: Build server
      run: ci/build-server.sh

    - name: Build rest
      run: ci/build-rest.sh

    - name: Test
      run: ci/test.sh

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: beefweb_linux
        if-no-files-found: error
        path: build/${{ env.BUILD_TYPE }}/*.tar.gz

  build_windows:

    runs-on: windows-2022

    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        arch:
        - Win32
        - x64

    env:
      BUILD_TYPE: RelWithDebInfo
      BUILD_ARCH: ${{ matrix.arch }}

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: '2022'
        arch: ${{ matrix.arch }}

    - name: Install tools
      run: cmd /c ci\install.cmd

    - name: Build
      run: cmd /c ci\build.cmd

    - name: Test
      run: cmd /c ci\test.cmd

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: beefweb_windows
        if-no-files-found: error
        path: |
          build\${{ env.BUILD_TYPE }}\*.fb2k-component
          build\${{ env.BUILD_TYPE }}\*.zip
